export interface CourseData {
  slug: string
  title: string
  icon: string
  color: string
  duration: string
  level: string
  mode: string
  shortDesc: string
  description: string
  techs: string[]
  outcomes: string[]
  internship: string
}

export const COURSES: CourseData[] = [
  {
    slug: 'full-stack-web-development',
    title: 'Full Stack Web Development',
    icon: '⚛️',
    color: '#6366f1',
    duration: '16 Weeks',
    level: 'Beginner → Advanced',
    mode: 'Online / Hybrid',
    shortDesc: 'Build production-ready web apps',
    description: 'Master frontend and backend development with React, Next.js, Node.js, and cloud deployment. Build 5+ production applications from scratch and gain hands-on experience with industry-standard tools and workflows used by top tech companies.',
    techs: ['React', 'Next.js', 'Node.js', 'PostgreSQL', 'AWS', 'TypeScript', 'Tailwind CSS', 'Git'],
    outcomes: ['Build 5+ production apps', 'Deploy on cloud infrastructure', 'Pass technical interviews', 'Full stack portfolio'],
    internship: 'Remote internship with startup partner',
  },
  {
    slug: 'generative-ai-engineering',
    title: 'Generative AI & AI Engineering',
    icon: '🤖',
    color: '#06b6d4',
    duration: '14 Weeks',
    level: 'Beginner → Advanced',
    mode: 'Online / Hybrid',
    shortDesc: 'Build AI-powered applications',
    description: 'Learn to build production AI applications using LLMs, RAG pipelines, and vector databases. Master prompt engineering, fine-tuning, and deploying AI SaaS products that solve real business problems.',
    techs: ['Python', 'LangChain', 'OpenAI', 'RAG', 'Vector DBs', 'FastAPI', 'Pinecone', 'HuggingFace'],
    outcomes: ['Build AI SaaS products', 'RAG pipeline development', 'LLM fine-tuning', 'AI product deployment'],
    internship: 'AI startup collaboration project',
  },
  {
    slug: 'graphic-designing',
    title: 'Graphic Designing',
    icon: '🎨',
    color: '#ec4899',
    duration: '10 Weeks',
    level: 'Beginner → Pro',
    mode: 'Online / Offline',
    shortDesc: 'Create stunning visual designs',
    description: 'Creative and detail-oriented Graphic Design training covering visually appealing graphics, social media creatives, branding materials, and UI concepts. Master Adobe Creative Suite, Figma, and Canva with strong understanding of color theory, typography, and modern design trends.',
    techs: ['Adobe Photoshop', 'Adobe Illustrator', 'Adobe XD', 'Canva', 'Figma', 'CorelDRAW', 'Typography', 'Branding & Visual Design'],
    outcomes: ['Design logos, banners & branding materials', 'Create UI mockups & app design concepts', 'Master motion graphics & video editing', 'Build complete brand identity systems'],
    internship: 'Design studio internship',
  },
  {
    slug: 'ui-ux-design',
    title: 'UI/UX Design',
    icon: '🖥️',
    color: '#f59e0b',
    duration: '12 Weeks',
    level: 'Beginner → Advanced',
    mode: 'Online / Hybrid',
    shortDesc: 'Design user-centered products',
    description: 'Master the complete product design process from user research to high-fidelity prototypes. Learn Figma, design systems, usability testing, and build a case study portfolio that lands you product design roles.',
    techs: ['Figma', 'Framer', 'Prototyping', 'Design Systems', 'Maze', 'FigJam'],
    outcomes: ['Full product design process', 'Design system creation', 'Case study portfolio', 'Design handoff skills'],
    internship: 'Product team internship',
  },
  {
    slug: 'backend-engineering',
    title: 'Backend Engineering',
    icon: '⚙️',
    color: '#10b981',
    duration: '14 Weeks',
    level: 'Intermediate',
    mode: 'Online',
    shortDesc: 'Build scalable server systems',
    description: 'Deep-dive into server-side architecture, API design, database optimization, and cloud infrastructure. Learn to build systems that handle millions of requests with proper caching, queuing, and microservices patterns.',
    techs: ['Node.js', 'FastAPI', 'PostgreSQL', 'Redis', 'Docker', 'GraphQL', 'RabbitMQ', 'Nginx'],
    outcomes: ['REST & GraphQL APIs', 'System design expertise', 'Scalable architecture', 'Database optimization'],
    internship: 'Backend role at product company',
  },
  {
    slug: 'ai-automation',
    title: 'AI Automation',
    icon: '⚡',
    color: '#8b5cf6',
    duration: '10 Weeks',
    level: 'Beginner → Advanced',
    mode: 'Online',
    shortDesc: 'Automate workflows with AI',
    description: 'Learn to build intelligent automation workflows that save businesses hundreds of hours. Master no-code platforms like n8n and Make.com alongside Python scripting and AI APIs to create powerful automated systems.',
    techs: ['n8n', 'Zapier', 'Python', 'Make.com', 'AI APIs', 'Google Apps Script', 'Airtable'],
    outcomes: ['Build automation workflows', 'AI-powered business tools', 'Client project delivery', 'SaaS automation'],
    internship: 'Automation agency internship',
  },
  {
    slug: 'devops-deployment',
    title: 'DevOps & Deployment',
    icon: '🐳',
    color: '#06b6d4',
    duration: '12 Weeks',
    level: 'Intermediate',
    mode: 'Online',
    shortDesc: 'Master cloud infrastructure',
    description: 'Dedicated DevOps Engineer training with expertise in automating deployment processes, managing cloud infrastructure, and implementing CI/CD pipelines. Master Docker, Kubernetes, AWS, Jenkins, and infrastructure automation to improve application scalability, reliability, and performance.',
    techs: ['Linux', 'AWS', 'Docker', 'Kubernetes', 'Jenkins', 'Git & GitHub', 'CI/CD Pipelines', 'Terraform', 'Ansible', 'Shell Scripting', 'Nginx', 'Prometheus', 'Grafana'],
    outcomes: ['Build & manage CI/CD pipelines', 'Deploy containerized apps with K8s', 'Automate infrastructure with Terraform', 'Monitor apps with Prometheus & Grafana'],
    internship: 'DevOps engineer role',
  },
  {
    slug: 'freelancing-accelerator',
    title: 'Freelancing Accelerator',
    icon: '💰',
    color: '#f59e0b',
    duration: '8 Weeks',
    level: 'All Levels',
    mode: 'Online',
    shortDesc: 'Launch your freelance career',
    description: 'Build a profitable freelancing business from scratch. Learn client acquisition, proposal writing, project management, and scaling strategies. Get hands-on practice with real client simulations on platforms like Upwork and Fiverr.',
    techs: ['Portfolio Building', 'Client Pitching', 'Upwork', 'Fiverr', 'LinkedIn', 'Notion', 'Stripe'],
    outcomes: ['Land first paying client', 'Build income pipeline', 'Scale freelance business', 'Professional portfolio'],
    internship: 'Real client project simulation',
  },
  {
    slug: 'digital-marketing',
    title: 'Digital Marketing',
    icon: '📢',
    color: '#f43f5e',
    duration: '12 Weeks',
    level: 'Beginner → Advanced',
    mode: 'Online / Hybrid',
    shortDesc: 'Master online marketing channels',
    description: 'Comprehensive digital marketing training covering SEO, SEM, social media marketing, email marketing, content strategy, and analytics. Learn to plan, execute, and measure ROI-driven campaigns across all major digital channels used by top brands and agencies.',
    techs: ['Google Ads', 'Meta Ads', 'SEO Tools', 'Google Analytics', 'Mailchimp', 'HubSpot', 'Canva', 'WordPress'],
    outcomes: ['Run paid ad campaigns', 'SEO & content strategy', 'Social media management', 'Marketing analytics & ROI'],
    internship: 'Digital agency internship',
  },
  {
    slug: 'video-editing',
    title: 'Video Editing & Production',
    icon: '🎬',
    color: '#a855f7',
    duration: '10 Weeks',
    level: 'Beginner → Pro',
    mode: 'Online / Offline',
    shortDesc: 'Create professional video content',
    description: 'Master video editing for YouTube, Instagram Reels, corporate content, and film projects. Learn industry-standard tools including Premiere Pro, DaVinci Resolve, and After Effects with hands-on project-based training from working professionals.',
    techs: ['Adobe Premiere Pro', 'DaVinci Resolve', 'After Effects', 'CapCut', 'Audacity', 'Color Grading', 'Motion Graphics', 'Sound Design'],
    outcomes: ['Edit professional videos', 'Color grading & correction', 'Motion graphics & VFX', 'YouTube & social media content'],
    internship: 'Production house internship',
  },
  {
    slug: 'photo-editing',
    title: 'Photo Editing & Photography',
    icon: '📸',
    color: '#14b8a6',
    duration: '8 Weeks',
    level: 'Beginner → Pro',
    mode: 'Online / Offline',
    shortDesc: 'Master photo editing & retouching',
    description: 'Professional photo editing and retouching training covering Adobe Photoshop, Lightroom, and advanced compositing techniques. Learn product photography editing, portrait retouching, real estate photo enhancement, and social media content creation.',
    techs: ['Adobe Photoshop', 'Lightroom', 'Camera RAW', 'Compositing', 'Retouching', 'Color Correction', 'Product Photography', 'AI Tools'],
    outcomes: ['Professional photo retouching', 'Product photography editing', 'Social media content', 'Photo manipulation mastery'],
    internship: 'Photography studio internship',
  },
  {
    slug: 'software-testing',
    title: 'Software Testing — Manual & Automation',
    icon: '🧪',
    color: '#22c55e',
    duration: '14 Weeks',
    level: 'Beginner → Advanced',
    mode: 'Online / Hybrid',
    shortDesc: 'Master QA testing & automation',
    description: 'Complete software testing training covering both manual and automation testing. Master Selenium, Cypress, Playwright, API testing with Postman, and CI/CD integration. Learn test planning, bug reporting, regression testing, and agile QA workflows used by top product companies.',
    techs: ['Selenium', 'Cypress', 'Playwright', 'Postman', 'JMeter', 'JIRA', 'TestNG', 'Jenkins', 'Git'],
    outcomes: ['Manual testing expertise', 'Automation framework design', 'API & performance testing', 'CI/CD test integration'],
    internship: 'QA engineer internship',
  },
  {
    slug: 'full-stack-python-development',
    title: 'Full Stack Python Development',
    icon: '🐍',
    color: '#3b82f6',
    duration: '16 Weeks',
    level: 'Beginner → Advanced',
    mode: 'Online / Hybrid',
    shortDesc: 'Build apps with Python & Django',
    description: 'Master full stack development with Python, Django, and React. Build production-ready web applications with REST APIs, database management, authentication, and cloud deployment. Python\'s versatility makes this stack ideal for web apps, data-driven products, and AI integration.',
    techs: ['Python', 'Django', 'Django REST Framework', 'React', 'PostgreSQL', 'Redis', 'Docker', 'AWS'],
    outcomes: ['Build full stack Python apps', 'REST API development', 'Database design & optimization', 'Cloud deployment skills'],
    internship: 'Python developer internship',
  },
  {
    slug: 'full-stack-java-development',
    title: 'Full Stack Java Development',
    icon: '☕',
    color: '#ef4444',
    duration: '16 Weeks',
    level: 'Beginner → Advanced',
    mode: 'Online / Hybrid',
    shortDesc: 'Enterprise Java development',
    description: 'Comprehensive Java full stack training covering Core Java, Spring Boot, Hibernate, and Angular/React frontend. Build enterprise-grade applications with microservices architecture, REST APIs, and cloud deployment — the stack used by banks, enterprises, and Fortune 500 companies.',
    techs: ['Java', 'Spring Boot', 'Hibernate', 'Angular', 'MySQL', 'Microservices', 'Maven', 'AWS'],
    outcomes: ['Enterprise Java applications', 'Spring Boot microservices', 'Frontend with Angular/React', 'Cloud-native development'],
    internship: 'Java developer internship',
  },
  {
    slug: 'java-development',
    title: 'Java Development',
    icon: '♨️',
    color: '#dc2626',
    duration: '14 Weeks',
    level: 'Beginner → Advanced',
    mode: 'Online / Hybrid',
    shortDesc: 'Core to advanced Java mastery',
    description: 'Deep Java development training from Core Java through advanced Spring framework. Master object-oriented programming, collections, multithreading, Spring Boot, REST APIs, and database connectivity. Ideal for students targeting roles at service-based and product companies.',
    techs: ['Core Java', 'Spring Framework', 'Spring Boot', 'JDBC', 'Maven', 'JUnit', 'MySQL', 'Git'],
    outcomes: ['Core Java mastery', 'Spring Boot applications', 'REST API development', 'Enterprise coding standards'],
    internship: 'Java backend internship',
  },
  {
    slug: 'python-development',
    title: 'Python Development',
    icon: '🐍',
    color: '#0ea5e9',
    duration: '12 Weeks',
    level: 'Beginner → Advanced',
    mode: 'Online / Hybrid',
    shortDesc: 'Python from basics to mastery',
    description: 'Master Python development from fundamentals to advanced application building. Cover OOP, data structures, web scraping, API development with Flask/FastAPI, database integration, and automation. Python is the most versatile language for web development, data science, AI, and automation.',
    techs: ['Python', 'Flask', 'FastAPI', 'SQLAlchemy', 'Pandas', 'NumPy', 'Web Scraping', 'REST APIs'],
    outcomes: ['Python application development', 'API building with Flask/FastAPI', 'Data processing skills', 'Automation scripting'],
    internship: 'Python developer internship',
  },
  {
    slug: 'mean-stack-development',
    title: 'MEAN Stack Development',
    icon: '🅰️',
    color: '#dd0031',
    duration: '14 Weeks',
    level: 'Beginner → Advanced',
    mode: 'Online / Hybrid',
    shortDesc: 'MongoDB, Express, Angular, Node.js',
    description: 'Master the MEAN stack — MongoDB, Express.js, Angular, and Node.js. Build modern single-page applications with TypeScript, reactive forms, and real-time features. MEAN stack is widely used in enterprise applications and offers strong career prospects in the corporate tech sector.',
    techs: ['MongoDB', 'Express.js', 'Angular', 'Node.js', 'TypeScript', 'RxJS', 'Mongoose', 'JWT Auth'],
    outcomes: ['Full MEAN stack applications', 'Angular component architecture', 'NoSQL database design', 'Real-time features with Socket.io'],
    internship: 'MEAN stack developer internship',
  },
  {
    slug: 'mern-stack-development',
    title: 'MERN Stack Development',
    icon: '⚛️',
    color: '#61dafb',
    duration: '14 Weeks',
    level: 'Beginner → Advanced',
    mode: 'Online / Hybrid',
    shortDesc: 'MongoDB, Express, React, Node.js',
    description: 'Master the MERN stack — MongoDB, Express.js, React, and Node.js. Build modern web applications with component-based architecture, state management, and RESTful APIs. MERN is the most popular JavaScript stack, used by startups and product companies for rapid development.',
    techs: ['MongoDB', 'Express.js', 'React', 'Node.js', 'Redux', 'Mongoose', 'JWT', 'Tailwind CSS'],
    outcomes: ['Full MERN stack applications', 'React state management', 'RESTful API development', 'Production deployment'],
    internship: 'MERN stack developer internship',
  },
  {
    slug: 'data-analytics',
    title: 'Data Analytics',
    icon: '📊',
    color: '#f97316',
    duration: '12 Weeks',
    level: 'Beginner → Advanced',
    mode: 'Online / Hybrid',
    shortDesc: 'Turn data into business insights',
    description: 'Master data analytics with Excel, SQL, Python, and visualization tools like Tableau and Power BI. Learn to collect, clean, analyze, and present data to drive business decisions. Data analysts are in high demand across every industry from e-commerce to healthcare.',
    techs: ['Excel Advanced', 'SQL', 'Python (Pandas)', 'Tableau', 'Power BI', 'Google Analytics', 'Statistics', 'Data Storytelling'],
    outcomes: ['Advanced Excel & SQL', 'Dashboard creation', 'Statistical analysis', 'Business intelligence reports'],
    internship: 'Data analyst internship',
  },
  {
    slug: 'data-science',
    title: 'Data Science & Machine Learning',
    icon: '🔬',
    color: '#8b5cf6',
    duration: '16 Weeks',
    level: 'Beginner → Advanced',
    mode: 'Online / Hybrid',
    shortDesc: 'ML models & predictive analytics',
    description: 'Comprehensive data science training covering statistics, machine learning, deep learning, and NLP. Master Python, scikit-learn, TensorFlow, and data visualization. Build predictive models, recommendation systems, and deploy ML applications for real business use cases.',
    techs: ['Python', 'scikit-learn', 'TensorFlow', 'Pandas', 'NumPy', 'Matplotlib', 'Jupyter', 'SQL', 'Keras'],
    outcomes: ['Machine learning models', 'Predictive analytics', 'Deep learning basics', 'ML model deployment'],
    internship: 'Data science internship',
  },
  {
    slug: 'cloud-computing',
    title: 'Cloud Computing & AWS',
    icon: '☁️',
    color: '#f59e0b',
    duration: '12 Weeks',
    level: 'Beginner → Advanced',
    mode: 'Online',
    shortDesc: 'Master AWS cloud infrastructure',
    description: 'Master cloud computing with AWS — the world\'s leading cloud platform. Learn EC2, S3, Lambda, RDS, VPC networking, IAM security, and cloud architecture. Prepare for AWS Solutions Architect certification while gaining hands-on experience deploying real applications on the cloud.',
    techs: ['AWS EC2', 'S3', 'Lambda', 'RDS', 'VPC', 'IAM', 'CloudFormation', 'CloudWatch', 'Route 53'],
    outcomes: ['AWS cloud architecture', 'Serverless applications', 'Cloud security & networking', 'AWS certification prep'],
    internship: 'Cloud engineer internship',
  },
  {
    slug: 'human-resource-management',
    title: 'Human Resource Management',
    icon: '👥',
    color: '#06b6d4',
    duration: '10 Weeks',
    level: 'Beginner → Advanced',
    mode: 'Online / Hybrid',
    shortDesc: 'Master HR operations & strategy',
    description: 'Professional HR management training covering recruitment, onboarding, payroll, compliance, performance management, and HR analytics. Learn to use modern HRMS tools and develop skills for roles in talent acquisition, employee engagement, and HR business partnering.',
    techs: ['HRMS Tools', 'Excel for HR', 'LinkedIn Recruiter', 'ATS Systems', 'Payroll Software', 'HR Analytics', 'Labor Laws', 'Performance Management'],
    outcomes: ['Recruitment & onboarding', 'Payroll & compliance', 'HR analytics & reporting', 'Employee engagement strategies'],
    internship: 'HR operations internship',
  },
  {
    slug: 'finance-courses',
    title: 'Finance & Accounting',
    icon: '💹',
    color: '#10b981',
    duration: '12 Weeks',
    level: 'Beginner → Advanced',
    mode: 'Online / Hybrid',
    shortDesc: 'Financial analysis & accounting',
    description: 'Practical finance and accounting training covering financial analysis, Tally, GST, income tax, Excel financial modeling, and business accounting. Prepare for roles in accounting firms, corporate finance, banking, and financial consulting with industry-relevant skills and certifications.',
    techs: ['Tally Prime', 'Advanced Excel', 'GST & Taxation', 'Financial Modeling', 'SAP FICO Basics', 'QuickBooks', 'Power BI for Finance', 'Bloomberg Basics'],
    outcomes: ['Financial statement analysis', 'GST & tax compliance', 'Financial modeling in Excel', 'Accounting software mastery'],
    internship: 'Finance & accounting internship',
  },
  {
    slug: 'english-communication',
    title: 'English Communication & Soft Skills',
    icon: '🗣️',
    color: '#ec4899',
    duration: '8 Weeks',
    level: 'All Levels',
    mode: 'Online / Offline',
    shortDesc: 'Professional English fluency',
    description: 'Build confident English communication skills for professional and corporate environments. Master spoken English, business writing, email etiquette, presentation skills, and interview communication. This program transforms your ability to express ideas clearly in workplace settings and client interactions.',
    techs: ['Spoken English', 'Business Writing', 'Email Etiquette', 'Presentation Skills', 'Group Discussion', 'Interview Prep', 'Public Speaking', 'Grammar Mastery'],
    outcomes: ['Fluent spoken English', 'Professional email & writing', 'Presentation confidence', 'Interview communication'],
    internship: 'Corporate communication project',
  },
  {
    slug: 'sales-and-marketing',
    title: 'Sales & Marketing Management',
    icon: '🎯',
    color: '#f97316',
    duration: '10 Weeks',
    level: 'Beginner → Advanced',
    mode: 'Online / Hybrid',
    shortDesc: 'Master B2B & B2C sales strategies',
    description: 'Comprehensive sales and marketing training covering B2B/B2C sales strategies, CRM management, lead generation, negotiation techniques, and marketing campaign planning. Develop skills for roles in business development, account management, and marketing management across industries.',
    techs: ['CRM (Salesforce/HubSpot)', 'Lead Generation', 'Sales Funnels', 'Negotiation', 'Market Research', 'Campaign Planning', 'Google Ads', 'Cold Outreach'],
    outcomes: ['B2B & B2C sales techniques', 'CRM & pipeline management', 'Lead generation strategies', 'Marketing campaign execution'],
    internship: 'Sales & marketing internship',
  },
]

export function getCourseBySlug(slug: string): CourseData | undefined {
  return COURSES.find(c => c.slug === slug)
}

export function getRelatedCourses(currentSlug: string): CourseData[] {
  return COURSES.filter(c => c.slug !== currentSlug).slice(0, 3)
}
